server_address: ":8080"
mongo_uri: "mongodb+srv://Akash:meakash7902@cluster0.sjlpojg.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
jwt_secret: "hey"

# Messaging configuration
messaging_type: "websocket" # or "nats"
nats_url: "nats://localhost:4222" # Required if messaging_type is "nats"
