name: Keep Backend Alive

on:
  schedule:
    - cron: "*/14 * * * *" # Runs every 14 minutes
  workflow_dispatch: # Optional: Allows manual triggering from GitHub

jobs:
  keep-alive:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: main # Explicitly checks out the main branch

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Run keep-alive script
      env:
        LOGI_KEEP_ALIVE_URL: ${{ vars.LOGI_KEEP_ALIVE_URL }}
      run: node ./.github/workflows/cron.js
